### PR TITLE
new write-content component

### PR DESCRIPTION
**Pull request by glenna-m**

### CODE REVIEW

**Comment by dbooth-boston** [comment]
LGTM

This looks helpful for debugging.

**Comment by catch-point** [comment]
Why not write to a file in the temporary directory, using os.tmpdir()? This way it could also be used in production environments (with read-only deployments).

**Comment by glenna-m** [comment]
I think you are referring to the unit test use of /tmp?  The os.tmpdir() API does not seem to work correctly on the Mac.  I get errors when I use it and then try to access the file created - that is why I am using /tmp.  I could create a directory for this kind of output under the test directory, if you like that approach better.   The write-content component itself just writes to whatever file the user specified.

**Comment by catch-point** [comment]
okay, LGTM then

**Pull request merged**
